name: "Build for Linux"

on:
  workflow_dispatch:
    branches: main


jobs:
  linux_build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: stable
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y ninja-build libgtk-3-dev cmake git libmpv-dev clang

      - name: Install Dependencies
        run: flutter pub get
            
      - name: Create .env file
        run: echo "CLIENT_ID = XXXXX\nCLIENT_SECRET = XXXX EOF" > assets/.env

      - name: Build Linux App
        run: flutter build linux --release --build-number ${{github.run_number}}

      - name: Zip Linux App
        run: |
          cd build/linux/x64/release/bundle
          zip -r echo_pulse_linux_v2.7.5_dev+${{github.run_number}}.zip .


      - name: Upload Linux App
        uses: actions/upload-artifact@v2
        with:
          name: echo_pulse_linux_dev
          path:  ECHOPULS/build/linux/x64/release/bundle/echo_pulse_linux_v2.7.5_dev+${{github.run_number}}.zip